name: Manual Build Extension

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build project (Auto-generate ZIP)
        run: pnpm zip  # 该命令会自动生成 latex_copy.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: latex-copy-browser-extension
          path: ./output/latex-copy-${verson}.zip  # 直接使用自动生成的 ZIP 文件